all:
	g++ alpha-beta.cpp -c
	g++ attack.cpp -c
	g++ board.cpp -c
	g++ move.cpp -c
	g++ init.cpp -c
	g++ io.cpp -c
	g++ eval.cpp -c
	g++ moveGenerator.cpp -c
	g++ main.cpp -c
	g++ *.o -o chess
run:
	./chess
clean:
	rm -f chess *.o
